services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # REST
      - "6334:6334"   # gRPC
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes: 
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO