paragraph_tests = {}

paragraph_tests["soccer_smallsize__2023__RoboTeam_Twente__0.pdf"] = [
    "1 Introduction",
    "2 Hardware",
    "2.1 Electronics",
    "Kicker-and-chipper board",
    "2.2 Mechanics",
    "3 Basestation",
    "3.1 Shortcomings r",
    "USB limitations",
    "Power limitations",
    "Peripheral limitations",
    "3.2 Design",
    "4 Software",
    "4.1 RoboTeam Embedded Messages",
    "The solution",
    "The evolution",
    "Open Source",
    "4.2 Artificial Intelligence",
    "High level simulator",
    "Machine learning",
    "Path Planning",
    "4.3 Control",
    "Dribbler as ball sensor",
    "Improved dribbler control",
    "References"
]

paragraph_tests["soccer_smallsize__2009__B-Smart__0.pdf"] = [
    "1 Introduction",
    "2 Hardware Architecture",
    "2.1 Vision Hardware",
    "2.2 Motors",
    "2.3 Electronic Design and Fabrication",
    "Foxboard",
    "Rabbitboard",
    "Kickerboard",
    "Motorboard",
    "2.4 Mechanical Design and Fabrication",
    "2.5 Batteries",
    "3 Software Architecture",
    "3.1 Software Environment",
    "3.2 Vision Software",
    "Image Processor",
    "Post Processor",
    "3.3 Agent",
    "3.4 Behavior Control",
    "XABSL",
    "Roles and Positioning",
    "Goalie",
    "Defender",
    "Criteria for covering opponents",
    "Striker without Ball",
    "Striker with Ball",
    "Dribbling",
    "Motion",
    "Interception",
    "Strategies",
    "3.5 Path-Planning",
    "Rapidly-Exploring Random Trees",
    "Dynamic Safety Search",
    "3.6 Motion Control",
    "3.7 Communication Control",
    "Setup",
    "Modular implementation",
    "Simultaneous usage",
    "Sequence numbers",
    "Hardware",
    "Comparison",
    "3.8 Simulator",
    "3.9 Logplayer",
    "4 Conclusion",
    "B-Smart team members",
    "References"
]

paragraph_tests["athome_domestic__2019__Austin_Villa__0.pdf"] = [
    "1 Introduction",
    "2 Software Overview",
    "2.1 Core Components",
    "LAAIR: A Layered Architecture for Autonomous Interactive Robots",
    "Knowledge Representation Subsystem",
    "PRISM",
    "2.2 Other Important Components",
    "Fast Perception",
    "3 Research Focus",
    "4 Innovative Technology",
    "4.1 Natural Language Understanding",
    "4.2 Grounded multimodal language learning",
    "4.3 Learning multi-step tasks from demonstration",
    "4.4 Robot-centric human activity recognition",
    "5 Re-usability",
    "6 Applicability to the Real World",
    "7 Conclusion",
    "References",
    "Addendum"
]

paragraph_tests["soccer_midsize__2010__IsePorto__0.pdf"] = [
    "1 Introduction",
	"2 Real-Time Publisher-Subscriber Communication",
	"3 Traction Control System",
	"3.1 Traction Control Hardware",
	"3.2 Traction System Architecture",
	"3.3 Characterization the of traction problems in the Middle Size League",
	"4 Inertial navigation system (INS)",
	"5 Kicking Device",
	"6 Vision System",
	"7 Control and Navigation Architecture",
	"8 Conclusions and Future Work",
	"9 Acknowledgement",
	"References"
]

paragraph_tests["soccer_humanoid_adult__2019__Tsinghua_Hephaestus__0.pdf"] = [
    "1 Introduction",
    "2 The Robot Design",
    "3 Software Architecture",
    "4 Vision",
    "5 Localization and Behavior Control",
    "6 Motion Control",
    "6.1 Gait Planning",
    "6.2 Stability Control",
    "6.3 Path Planning",
    "7 Conclusion",
    "7.1 Team Members",
    "References"
]

paragraph_tests["soccer_humanoid_kid__2019__Ichiro__0.pdf"] = [
    "1 Introduction",
    "2 Electrical Hardware Overview",
    "3 Mechanical Design",
    "3.1 Arata",
    "3.2 Arata V.2",
    "3.3 Ithaaro",
    "4 Computer Vision",
    "4.1 Object Detection on the Soccer Field",
    "4.2 Localization Method",
    "5 Robot Behavior and Strategy",
    "5.1 Robot Behavior",
    "5.2 Robot Monitoring Software",
    "References"
]

paragraph_tests["soccer_humanoid_teen__2019__MRL__0.pdf"] = [
    "1 Introduction",
    "2 Overview of the System",
    "2.1 Control manager",
    "Controller Board.",
    "Sensor Board.",
    "2.2 Strain Gauge",
    "3 Goal Detection",
    "4 Motion Control",
    "4.1 Simulation",
    "4.2 Motor driver",
    "4.3 Yaw moment compensation",
    "4.4 Push recovery",
    "4.5 Kicking",
    "5 Conclusion",
    "References"
]

paragraph_tests["industrial_atwork__2021___AutonOHM__0.pdf"] = [
    "1 Introduction",
    "2 AutonOHM",
    "3 Hardware Description",
    "3.1 Sensors",
    "Lidars",
    "Cameras",
    "3.2 PC",
    "3.3 PSU",
    "3.4 Manipulator",
    "Arm",
    "Gripper",
    "3.5 Other",
    "Inventory",
    "Network Setup",
    "RGB Feedback",
    "4 Software Description",
    "4.1 Driver",
    "Base Platform",
    "Laser Scanner",
    "Camera",
    "Dynamixel Workbench",
    "RGB LED",
    "4.2 Model",
    "Laser Filter",
    "Ohm PF",
    "Move Base",
    "Pose Approach",
    "NN - Barriertape",
    "NN - Objects",
    "4.3 Controller",
    "Joy Control",
    "Barriertape Control",
    "Arm Control",
    "Perception Control",
    "4.4 Brain",
    "Worldmodel",
    "Status Monitor",
    "Task Manager",
    "Task Executioner",
    "5 Conclusion and Future Work",
    "References"
]

paragraph_tests["soccer_simulation_2d__2022__FRA-UNIted__0.pdf"] = [
    "1 Introduction",
    "1.1 Design Principles",
    "1.2 The FRA-UNIted Agent",
    "2 Team-Internal Reflection in Regard to the Covid-19 Pandemic",
    "2.1 Team Activity and Statistics",
    "2.2 Teaching Experiment: Redevelop the Entire Play Without Ball",
    "3 Diversified RoboCup Training Protocols on a Distributed Architecture",
    "4 Aggressive Defense Behavior Utilizing Low-Level Opponent Action Predictions",
    "5 Conclusion",
    "References"
]

paragraph_tests["industrial_logistics__2019__Solidus__0.pdf"] = [
    "1 Introduction",
    "2 Technical Institute of Applied Science HFTM",
    "3 Didactic Concept",
    "4 The Team Solidus",
    "5 Technology",
    "5.1 Software",
    "5.2 Hardware",
    "6 Successes of the Team",
    "6.1 RoboCup 2017 Nagoya Japan",
    "6.2 RoboCup 2017 Montreal Canada",
    "7 Rulebook Confirmation"
]


